"""The monster scope recorded in data/roster.v1.json."""

from .roster import load_roster

# The roster is data (data/roster.v1.json), regenerated by the roster command.
EXPECTED_ENEMY_IDS = tuple(e["enemyId"] for e in load_roster()["enemies"])
NATIVE_OWNERS = {e["enemyId"]: e["nativeOwner"] for e in load_roster()["enemies"]}
